project_id = "notes_brain"

[api]
enabled = true
port = 65421
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 65422
shadow_port = 65420
major_version = 15

[studio]
enabled = true
port = 65423
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 65424
